services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: api-build
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - type: bind
        source: ./images
        target: /app/client/public/images
      - type: volume
        source: uploads
        target: /app/uploads
      - type: volume
        source: logs
        target: /app/api/logs

  client:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: nginx-client
    container_name: LibreChat-NGINX
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
  
  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: data-node
        target: /data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - type: volume
        source: meili_data_v1.12
        target: /meili_data

  vectordb:
    image: pgvector/pgvector:0.8.0-pg15-trixie
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - type: volume
        source: pgdata2
        target: /var/lib/postgresql/data

  rag_api:
    # --- KORREKTUR: 'build:'-Block entfernt ---
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

volumes:
  pgdata2:
  uploads:
  logs:
  data-node:
  meili_data_v1.12:
